[package]
name = "Brickbyte"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
glutin = "0.32.3"
glow = "0.16"
egui = "0.33.2"
egui-winit = "0.33.2"
egui_glow = "0.33.2"
glam = "0.30.5"
rand = "0.9.2"