[package]
name = "Brickbyte"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
glutin = "0.32.3"
glow = "0.16"
egui = "0.32.3"
egui-winit = "0.27.2"
egui_glow = "0.31.1"
glam = "0.30.5"
bytemuck = "1.23.2"